/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface blogPostDeleteSchema {
  postId: string;
}

export interface blogPostSchema {
  content: string;
  imgUrl?: string;
  tags?: string[];
  title: string;
  userId: string;
}

export interface blogPostUpdateSchema {
  content?: string;
  title?: string;
}
